export {
    germanAdjectivesList1, germanAdjectivesList2, germanAdjectivesList3, germanAdjectivesList4, germanAdjectivesList5, germanAdjectivesList6, germanAdjectivesList7, germanAdjectivesList8, germanAdjectivesList9, germanAdjectivesList10
};

let germanAdjectivesList1 = [
    "gut", "neu", "besser", "unterer, untere, unteres", "groß", "bester, beste, bestes", "weit", "ganz", "deutsch", "alt", "rund", "klein", "hoch", "jung", "weiterer, weitere, weiteres", "lang", "wichtig", "nächste", "möglich", "eigen", "stark", "kurz", "spät", "einfach", "schnell", "gerade", "gleich", "natürlich", "richtig", "genau", "schön", "sicher", "eigentlich", "später", "eben", "schwer", "klar", "einzeln", "bekannt", "letzter, letzte, letztes", "leicht", "hintere", "wirklich", "frei", "früh", "schlecht", "unterschiedlich", "deutlich", "allgemein", "einzig", "rechter, rechte, rechtes", "gemeinsam", "nahe, nah", "voll", "direkt", "rot", "offen", "verschieden", "sozial", "besonderer, besondere, besonderes", "meist", "gewiss", "öffentlich", "europäisch", "halb", "häufig", "wahrscheinlich", "wesentlich", "ähnlich", "schwarz", "völlig", "gering", "schwierig", "persönlich", "praktisch", "modern", "amerikanisch", "tief", "tatsächlich", "zusätzlich", "wirtschaftlich", "relativ", "interessant", "gleichzeitig", "grün", "weiß", "speziell", "gesamt", "bloß", "eng", "entscheidend", "technisch", "langsam", "ständig", "notwendig", "rein", "falsch", "englisch", "wissenschaftlich", "normal", "französisch"
];

let germanAdjectivesList2 = [
    "fremd", "selten", "wahr", "tot", "privat", "fest", "positiv", "zentral", "fertig", "hart", "vorhanden", "breit", "grundsätzlich", "künftig", "knapp", "bestimmt", "historisch", "aktuell", "übrig", "schlimm", "schlimmer", "dunkel", "lieb", "offenbar", "erfolgreich", "zahlreich", "weltweit", "konkret", "geboren", "regelmäßig", "aktiv", "menschlich", "kalt", "ehemalig", "erforderlich", "jeweilig", "kulturell", "heutig", "unabhängig", "Schweizer", "unmittelbar", "finanziell", "ruhig", "klassisch", "bewusst", "heiß", "echt", "teuer", "nötig", "toll", "erneut", "gesellschaftlich", "täglich", "üblich", "national", "absolut", "leer", "individuell", "blau", "rasch", "russisch", "verantwortlich", "erheblich", "zuständig", "ernst", "typisch", "zufrieden", "warm", "schwach", "dick", "linker, linke, linkes", "niedrig", "bereit", "traditionell", "gesetzlich", "negativ", "österreichisch", "glücklich", "beruflich", "selbstverständlich", "offiziell", "streng", "fein", "ausländisch", "bisherig", "ausschließlich", "laut", "tätig", "sinnvoll", "ursprünglich", "jährlich", "frisch", "weitgehend", "intensiv", "heftig", "automatisch", "gefährlich", "vollständig", "eindeutig", "scharf"
];

let germanAdjectivesList3 = [
    "offensichtlich", "berühmt", "politisch", "international", "still", "froh", "britisch", "kritisch", "italienisch", "staatlich", "reich", "riesig", "günstig", "dicht", "nett", "gesund", "westlich", "extrem", "freundlich", "total", "unbekannt", "stolz", "endgültig", "elektronisch", "sichtbar", "doppelt", "billig", "rechtlich", "damalig", "angeblich", "kräftig", "wild", "bunt", "ideal", "freiwillig", "dringend", "heilig", "regional", "angenehm", "eventuell", "medizinisch", "aufmerksam", "global", "ehrlich", "gelb", "spanisch", "vielfältig", "trocken", "wunderbar", "sportlich", "türkisch", "katholisch", "langfristig", "äußerer, äußere, äußeres", "ordentlich", "demokratisch", "perfekt", "maximal", "enorm", "kurzfristig", "optimal", "massiv", "gerecht", "umfangreich", "generell", "lokal", "digital", "spannend", "komplett", "zukünftig", "gezielt", "schade", "musikalisch", "lustig", "unglaublich", "durchschnittlich", "stabil", "golden", "städtisch", "beliebt", "herzlich", "ungewöhnlich", "attraktiv", "weiblich", "ausdrücklich", "intern", "mehrfach", "ausführlich", "hervorragend", "stellvertretend", "evangelisch", "nachhaltig", "wunderschön", "wertvoll", "verfügbar", "divers", "kreativ", "super", "extern", "heimisch"
];

let germanAdjectivesList4 = [
    "professionell", "sozialistisch", "chinesisch", "kostenlos", "monatlich", "gemütlich", "gespannt", "mobil", "voraussichtlich", "erhältlich", "olympisch", "langjährig", "willkommen", "hochwertig", "interessiert", "konzentriert", "ausreichend", "folgend", "geeignet", "begeistert", "beschäftigt", "sogenannt", "überlegen", "verboten", "geschlossen", "gar", "wert", "-jährig", "innerer, innere, inneres", "ungefähr", "okay", "krank", "leise", "komplex", "obere, oberen", "geistig", "böse", "außen", "militärisch", "theoretisch", "hell", "hauptsächlich", "gegenwärtig", "zeitlich", "mittlerer, mittlere, mittleres", "spezifisch", "elektrisch", "grau", "chemisch", "künstlerisch", "biologisch", "abhängig", "Wiener", "schuld", "selb(st)ständig", "umgekehrt", "ökonomisch", "arbeitslos", "religiös", "mächtig", "schriftlich", "unmöglich", "überwiegend", "bedeutend", "christlich", "räumlich", "körperlich", "angemessen", "dünn", "sprachlich", "sonstig", "vorsichtig", "entfernt", "derartig", "schmal", "arabisch", "weich", "ewig", "unheimlich", "traurig", "arm", "gewaltig", "gegenseitig", "grundlegend", "verheiratet", "inhaltlich", "exakt", "künstlich", "sauber", "gelegentlich", "gewohnt", "bay(e)risch", "parallel", "literarisch", "grob", "vergleichbar", "flach", "kompliziert", "allmählich", "strategisch"
];

let germanAdjectivesList5 = [
    "müde", "schrecklich", "konservativ", "kühl", "nackt", "physikalisch", "touristisch", "vielfach", "gewöhnlich", "israelisch", "braun", "einheitlich", "islamisch", "real", "statistisch", "zufällig", "dramatisch", "erkennbar", "komisch", "fern", "objektiv", "juristisch", "sorgfältig", "seltsam", "vernünftig", "gefangen", "mathematisch", "griechisch", "radikal", "winzig", "systematisch", "vertraut", "verrückt", "ernsthaft", "erstaunlich", "glatt", "scheinbar", "hübsch", "sanft", "wirksam", "akademisch", "experimentell", "primär", "rechtzeitig", "verständlich", "übel", "vorübergehend", "bequem", "schlicht", "ökologisch", "vollkommen", "unendlich", "abstrakt", "dumm", "geheim", "lebendig", "indirekt", "subjektiv", "relevant", "analog", "heimlich", "dynamisch", "moralisch", "indisch", "prinzipiell", "locker", "potenziell", "Münchner, Münchener", "problematisch", "steil", "südlich", "akut", "ausgeprägt", "blöd", "einig", "jetzig", "wahnsinnig", "virtuell", "zugänglich", "außerordentlich", "ausgezeichnet", "eigenständig", "blind", "denkbar", "feucht", "geistlich", "intellektuell", "materiell", "kontinuierlich", "konsequent", "korrekt", "psychisch", "merkwürdig", "mündlich", "pädagogisch", "unsicher", "auswärtig", "beliebig", "derzeitig", "furchtbar"
];

let germanAdjectivesList6 = [
    "friedlich", "genetisch", "neugierig", "restlich", "umstritten", "verdächtig", "effektiv", "gründlich", "einsam", "konstant", "jahrelang", "liberal", "japanisch", "langweilig", "optisch", "logisch", "schief", "nervös", "organisch", "peinlich", "spontan", "unzählig", "wütend", "bescheiden", "flexibel", "deutschsprachig", "dauerhaft", "nachfolgend", "kirchlich", "herrlich", "klug", "süß", "unangenehm", "vorläufig", "behindert", "angewiesen", "anstrengend", "einmalig", "elegant", "formal", "gültig", "klinisch", "nützlich", "palästinensisch", "schuldig", "stetig", "organisatorisch", "unklar", "sexuell", "vergeblich", "anwesend", "empfindlich", "einheimisch", "betrieblich", "bürgerlich", "fröhlich", "großzügig", "konventionell", "mühsam", "qualitativ", "reichlich", "psychologisch", "nördlich", "schwanger", "stumm", "vermehrt", "strukturell", "zulässig", "alltäglich", "charakteristisch", "detailliert", "dauernd", "beträchtlich", "einseitig", "dankbar", "diskret", "einverstanden", "fließend", "mechanisch", "männlich", "lauter", "örtlich", "polnisch", "medial", "physisch", "präzise", "symbolisch", "treu", "wach", "vorig", "vermeintlich", "ärztlich", "alternativ", "aufwändig, aufwendig", "bemerkenswert", "besorgt", "effizient", "düster", "chronisch", "erreichbar"
];

let germanAdjectivesList7 = [
    "emotional", "landwirtschaftlich", "intelligent", "maßgeblich", "nass", "realistisch", "pakistanisch", "operativ", "sachlich", "philosophisch", "überflüssig", "unsichtbar", "verbindlich", "zwangsläufig", "verlegen", "aufrecht", "auffällig", "blond", "berufstätig", "drastisch", "endlos", "fachlich", "explizit", "fotografisch", "illegal", "gleichsam", "gleichmäßig", "industriell", "identisch", "mild", "permanent", "regelrecht", "sowjetisch", "spürbar", "tödlich", "steuerlich", "unverändert", "starr", "unverzüglich", "unwahrscheinlich", "vertraglich", "amtlich", "außergewöhnlich", "belgisch", "blass", "bedeutsam", "elementar", "flüchtig", "minimal", "nachträglich", "mutmaßlich", "naturwissenschaftlich", "schlank", "schulisch", "unglücklich", "therapeutisch", "strikt", "zuverlässig", "vorzeitig", "ästhetisch", "bitter", "einstig", "fällig", "flüssig", "interkulturell", "harmlos", "glänzend", "hässlich", "nachdenklich", "ländlich", "optimistisch", "schräg", "schmutzig", "unerwartet", "absurd", "hilflos", "großartig", "ostdeutsch", "östlich", "niederländisch", "radioaktiv", "technologisch", "solide", "unerträglich", "westdeutsch", "geschmeidig", "mutig", "nervig", "sonnig", "farbig", "fraglich", "erleichtert", "schmerzhaft", "schwul", "unweigerlich", "rau", "begrenzt", "unverständlich", "schädlich", "niedlich"
];

let germanAdjectivesList8 = [
    "rosa", "romantisch", "dezent", "frech", "ärgerlich", "förmlich", "köstlich", "strafbar", "geehrt", "vegetarisch", "kahl", "fair", "roh", "schick", "populär", "geöffnet", "spitz", "trist", "gratis", "reif", "hoffnungslos", "fit", "defekt", "motiviert", "besetzt", "verwandt", "lecker", "feige", "verzweifelt", "mager", "kompetent", "fett", "pauschal", "aufregend", "sauer", "haltbar", "lose", "lautstark", "klasse", "zweifach", "fleißig", "hungrig", "erwachsen", "orange", "deutschlandweit", "entschlossen", "satt", "zügig", "gleichberechtigt", "fantastisch", "aufrichtig", "misstrauisch", "pünktlich", "einzigartig", "befriedigend", "sinnlos", "unterhaltsam", "überzeugend", "prima", "schlau", "aggressiv", "untersagt", "albern", "verwirrt", "passiv", "dubios", "matt", "ratlos", "verpflichtend", "sympathisch", "hartnäckig", "angespannt", "vorder", "telefonisch", "betrunken", "sparsam", "äußerlich", "heil", "höflich", "tatkräftig", "preiswert", "ausgebildet", "nüchtern", "spitze", "faul", "original", "stressig", "farbenfroh", "lächerlich", "witzig", "markant", "stilistisch", "vertikal", "oberflächlich", "getrennt", "skeptisch", "vorherig", "passend", "eiskalt", "europaweit" 
];

let germanAdjectivesList9 = [
    "dreckig", "eilig", "bar", "kaputt", "geschieden", "ängstlich", "verletzt", "riskant", "bedingungslos", "gebraucht", "darauffolgend", "geschickt", "weise", "verkehrt", "heiter", "leiblich", "-stündig", "imposant", "ehrgeizig", "begabt", "formell", "umweltfreundlich", "stundenlang", "parat", "ersichtlich", "aufgeregt", "feierlich", "schüchtern", "fragwürdig", "steif", "tragbar", "erneuerbar", "regenerativ", "durchsichtig", "transparent", "separat", "wöchentlich", "überhöht", "berechtigt", "gegnerisch", "vertraulich", "kostenfrei", "tragisch", "kostbar", "zuversichtlich", "doof", "erfolglos", "geographisch", "empirisch", "kommunikativ", "methodisch", "linear", "motorisch", "kognitiv", "quantitativ", "gentechnisch", "verschwenderisch", "unmotiviert", "vergnügt", "geizig", "todkrank", "tolerant", "wohnlich", "rutschig", "befreit", "süchtig", "stumpf", "dumpf", "schlapp", "unentschieden", "altmodisch", "gierig", "ahnungslos", "verabredet", "unzuverlässig", "demotiviert", "möbliert", "beige", "horizontal", "synonym", "einfallslos", "taub", "neblig", "füllig", "unschlüssig", "durstig", "beengt", "teilbar", "schwerhörig", "stur", "regnerisch", "allergisch", "brünett", "dunkelhaarig", "unzertrennlich", "senkrecht", "waagerecht", "eckig", "lila", "überstürzt"
];

let germanAdjectivesList10 = [
    "behaart", "unpersönlich", "haarig", "sprudelnd", "zweifelsfrei", "pleite", "unhöflich", "hilfsbereit", "ansteckend", "entspannend", "ekelhaft", "unheilbar", "bedacht", "missmutig", "abwesend", "verpflichtet", "bewölkt", "umgangssprachlich", "geräumig", "violett", "wertlos", "pessimistisch", "ungemütlich", "ledig", "fabelhaft", "pflegeleicht", "wohnungslos", "volljährig", "unentschlossen", "erschöpft", "verliebt", "salzig", "erkältet", "unordentlich", "windig", "rothaarig", "beleidigt", "blitzschnell", "gelenkig", "wehmütig", "ungeduldig", "krumm", "widerlich", "verwitwet", "abergläubisch", "mollig", "schlagfertig", "erlaubt", "vulgär", "obdachlos", "quadratisch", "zahm", "eifersüchtig", "spiegelverkehrt"
];