export {
    germanVerbsList1, germanVerbsList2, germanVerbsList3, germanVerbsList4, germanVerbsList5, germanVerbsList6, germanVerbsList7, germanVerbsList8, germanVerbsList9, germanVerbsList10, germanVerbsList11, germanVerbsList12, germanVerbsList13, germanVerbsList14
};

let germanVerbsList1 = [
    "sein(i)", "werden(i)", "haben(i)", "können(i)", "sagen", "geben(i)", "müssen(i)", "sollen(i)", "gehen(i)", "kommen(i)", "wollen(i)", "machen", "stehen(i)", "finden(i)", "lassen(i)", "sehen(i)", "bleiben(i)", "liegen(i)", "zeigen", "dürfen(i)", "stellen", "nehmen(i)", "bringen(i)", "erklären", "spielen", "halten(i)", "führen", "wissen(i)", "setzen", "sich setzen", "bekommen(i)", "heißen(i)", "tun(i)", "gehören", "erhalten(i)", "beginnen(i)", "mögen(i)", "sprechen(i)", "gelten(i)", "arbeiten", "brauchen", "bieten(i)", "fahren(i)", "schreiben(i)", "leben", "bestehen(i)", "denken(i)", "laufen(i)", "sitzen(i)", "entsprechen(i)", "glauben", "nennen(i)", "scheinen(i)", "ziehen(i)", "treffen(i)", "entstehen(i)", "fragen", "sich fragen", "fallen(i)", "legen", "(sich) vorstellen", "meinen", "suchen", "erreichen", "handeln", "tragen(i)", "lesen(i)", "schaffen", "kennen(i)", "darstellen", "verlieren(i)", "entwickeln", "reden", "erkennen(i)", "erscheinen(i)", "aussehen(i)", "folgen", "anfangen(i)", "versuchen", "bilden", "lernen", "erwarten", "betreffen(i)", "wohnen", "warten", "verstehen(i)", "helfen(i)", "gewinnen(i)", "fühlen", "interessieren", "sich interessieren", "erinnern", "sich erinnern", "schließen(i)", "anbieten(i)", "ergeben(i)", "sich ergeben(i)", "bedeuten", "verbinden(i)", "studieren", "fehlen"
];

let germanVerbsList2 = [
    "ansehen(i)", "steigen(i)", "nutzen", "vergleichen(i)", "sich verlassen(i)", "verlassen(i)", "schauen", "ausgehen(i)", "geschehen(i)", "wachsen(i)", "beschreiben(i)", "einsetzen", "ändern", "annehmen(i)", "bezeichnen", "wirken", "planen", "sich befinden(i)", "rufen(i)", "passieren", "bestimmen", "schlagen(i)", "aufnehmen(i)", "öffnen", "fordern", "gefallen(i)", "treten(i)", "übernehmen(i)", "lachen", "verwenden(i)", "verändern", "wählen", "erfolgen", "betrachten", "enthalten(i)", "sich enthalten(i)", "kaufen", "gelingen(i)", "(sich) entscheiden(i)", "vergessen(i)", "erfahren(i)", "stattfinden(i)", "feststellen", "trinken(i)", "bewegen(i)", "verschwinden(i)", "dienen", "berichten", "auftreten(i)", "beobachten", "stimmen", "holen", "rechnen", "erleben", "sterben(i)", "unterscheiden(i)", "essen(i)", "reichen", "werfen(i)", "leisten", "vorliegen(i)", "verlangen", "hoffen", "bauen", "wünschen", "hängen(i)", "zählen", "dauern", "teilen", "sich freuen", "bezahlen", "stecken", "bitten(i)", "besuchen", "sorgen", "sich sorgen", "beziehen(i)", "ankommen(i)", "erhöhen", "spüren", "melden", "betonen", "besitzen(i)", "erfüllen", "sich beteiligen", "merken", "umfassen", "richten", "sich eignen", "passen", "unterstützen", "beschäftigen", "lösen", "sich trennen", "trennen", "lieben", "antworten", "einstellen", "genügen", "erzählen"
];

let germanVerbsList3 = [
    "bestätigen", "durchführen", "untersuchen", "aufbauen", "verkaufen", "erlauben", "drücken", "eingehen(i)", "blicken", "treiben(i)", "drohen", "behandeln", "überzeugen", "benutzen", "versprechen(i)", "entdecken", "klingen(i)", "reagieren", "verdienen", "kosten", "drehen", "überraschen", "betreiben(i)", "heben(i)", "fliegen(i)", "vertreten(i)", "stoßen(i)", "schicken", "wechseln", "ermöglichen", "leiden(i)", "herstellen", "benötigen", "zahlen", "liefern", "abschließen(i)", "stammen", "verhindern", "erwähnen", "überlegen", "reisen", "aufgeben(i)", "singen(i)", "betragen(i)", "verzichten", "greifen(i)", "geraten(i)", "einrichten", "begründen", "verfügen", "vorbereiten", "schützen", "stören", "feiern", "vermitteln", "berücksichtigen", "funktionieren", "behaupten", "ausschließen(i)", "diskutieren", "erheben(i)", "gründen", "herrschen", "verfolgen", "ablehnen", "fördern", "zwingen(i)", "ansprechen(i)", "entfernen", "beachten", "sichern", "fassen", "wenden(i)", "vermeiden(i)", "organisieren", "informieren", "sich kümmern", "prägen", "sinken(i)", "vorsehen(i)", "ankündigen", "verletzen", "einladen(i)", "empfehlen(i)", "eröffnen", "sich bemühen", "beschließen(i)", "schätzen", "prüfen", "leiten", "sich konzentrieren", "anlegen", "verpflichten", "festlegen", "beitragen(i)", "brechen(i)", "übertragen(i)", "präsentieren", "anschauen", "füllen"
];

let germanVerbsList4 = [
    "sich vornehmen(i)", "verteilen", "abgeben(i)", "verbessern", "messen(i)", "erzielen", "durchsetzen", "sammeln", "ersetzen", "kämpfen", "warnen", "verbringen(i)", "hinweisen", "gestalten", "zulassen(i)", "teilnehmen(i)", "beenden", "scheitern", "reduzieren", "einführen", "angehen(i)", "äußern", "pflegen", "versichern", "gelangen", "begleiten(i)", "besetzen", "akzeptieren", "verweisen", "erweisen", "produzieren", "bestellen", "springen(i)", "starten", "erweitern", "ermitteln", "aufstellen", "überprüfen", "kritisieren", "erwerben(i)", "ergänzen", "zerstören", "üben", "schießen(i)", "behalten(i)", "belegen", "hören", "lauten", "stürzen", "umgehen(i)", "absehen(i)", "vermuten", "beweisen", "verlaufen(i)", "sich verlaufen(i)", "landen", "retten", "schenken", "genießen(i)", "fließen(i)", "kontrollieren", "bedienen", "töten", "vorlegen", "verabschieden", "rücken", "verbieten(i)", "fortsetzen", "klappen", "beantworten", "erläutern", "verraten(i)", "zeichnen", "mitteilen", "enden", "betreuen", "sparen", "umsetzen", "anzeigen", "begrüßen", "veröffentlichen", "befürchten", "achten", "erledigen", "anpassen", "erstellen", "beraten(i)", "klären", "speichern", "engagieren", "steigern", "versorgen", "investieren", "antreten(i)", "finanzieren", "testen", "verschieben(i)", "unterliegen(i)", "erteilen", "empfangen(i)"
];

let germanVerbsList5 = [
    "stärken", "weisen", "widmen", "sich lohnen", "vergeben(i)", "bereiten", "ausbauen", "absolvieren", "laden(i)", "errichten", "lehnen", "verleihen(i)", "bewerten", "loben", "hinterlassen(i)", "registrieren", "senden(i)", "verurteilen", "fangen(i)", "profitieren", "danken", "kündigen", "verteidigen", "beantragen(i)", "trainieren", "anmelden", "sperren", "bestreiten(i)", "übergeben(i)", "werben(i)", "stoppen", "veranstalten", "verpassen", "locken", "kommentieren", "installieren", "vergehen(i)", "kriegen", "zunehmen(i)", "sich verhalten(i)", "vorkommen(i)", "schlafen(i)", "lächeln", "ausreichen", "schweigen(i)", "kochen", "angeben(i)", "festhalten(i)", "wiederholen", "schieben(i)", "auftauchen", "zurückkommen(i)", "beeinflussen", "existieren", "anwenden(i)", "empfinden(i)", "einfallen(i)", "schneiden(i)", "nicken", "aufstehen(i)", "beschränken", "verstärken", "begreifen(i)", "abhängen(i)", "zurückkehren", "sich unterhalten(i)", "weitergehen(i)", "definieren", "orientieren", "schreien(i)", "einnehmen(i)", "bemerken", "aufweisen", "abnehmen(i)", "heiraten", "nachdenken(i)", "auslösen", "formulieren", "drängen", "ausmachen", "regeln", "binden(i)", "erfassen", "anziehen(i)", "anrufen(i)", "aufhören", "begrenzen", "reißen(i)", "fürchten", "berechnen", "eintreten(i)", "ablaufen(i)", "ausdrücken", "anschließen(i)", "zurückgehen(i)", "streichen", "bedürfen(i)", "herauskommen(i)", "zukommen(i)", "auffallen(i)"
];

let germanVerbsList6 = [
    "betreten(i)", "ausüben", "überleben", "erzeugen", "realisieren", "verbreiten", "begegnen", "erfordern", "brennen(i)", "verbergen(i)", "packen", "erschrecken(i)", "senken", "anerkennen(i)", "zurückziehen(i)", "schütteln", "erleichtern", "beurteilen", "wahrnehmen(i)", "unterrichten", "belasten", "nachweisen", "verursachen", "vertrauen", "unterbrechen(i)", "aussprechen(i)", "beherrschen", "vorschlagen(i)", "einschränken", "leuchten", "mitnehmen(i)", "zusammenfassen", "ausrichten", "waschen(i)", "integrieren", "starren", "einkaufen", "ausbilden", "anhalten(i)", "gucken", "verstecken", "unternehmen(i)", "mitbringen(i)", "auflösen", "anstreben", "hingehen(i)", "beruhigen", "ausführen", "fügen", "schwimmen(i)", "begeistern", "deuten", "vereinbaren", "probieren", "malen", "wagen", "weinen", "übersetzen", "steuern", "auswählen", "auffordern", "enttäuschen", "eintragen(i)", "träumen", "stützen", "voraussetzen", "umdrehen", "zugeben(i)", "ansetzen", "bevorzugen", "zuhören", "zusammenhängen(i)", "aufwachsen(i)", "kennzeichnen", "entschuldigen", "zitieren", "gefährden", "tanzen", "wandern", "ausgeben(i)", "beeindrucken", "aussetzen", "gewähren", "befragen", "aufheben(i)", "zuordnen", "sich entschließen(i)", "sich befassen", "lehren", "garantieren", "berechtigen", "rühren", "mischen", "angucken", "wecken", "vereinigen", "beruhen", "anhören", "bewirken", "aufführen"
];

let germanVerbsList7 = [
    "herausstellen", "anstellen", "bedenken(i)", "einbringen(i)", "rechtfertigen", "sich verlieben", "befreien", "aufsteigen(i)", "besprechen(i)", "aufpassen", "einziehen(i)", "riechen(i)", "überlassen(i)", "vorgeben(i)", "zögern", "vorhaben(i)", "aufhalten(i)", "ableiten", "berühren", "ausstatten", "einräumen", "ergreifen(i)", "entlassen(i)", "regieren", "trauen", "zurückführen", "sich wehren", "aufgehen(i)", "ausziehen(i)", "aussuchen", "zugehen(i)", "analysieren", "ahnen", "erarbeiten", "schalten", "verarbeiten", "sich wundern", "versehen(i)", "ausfallen(i)", "abbauen", "abwarten", "einbeziehen(i)", "einbauen", "interpretieren", "ordnen", "neigen", "schmecken", "raten(i)", "zusammensetzen", "ablegen", "anregen", "aufregen", "abstimmen", "(sich) ärgern", "bedecken", "beugen", "entziehen(i)", "ausweisen", "erbringen(i)", "erfinden(i)", "faszinieren", "gewöhnen", "klagen", "rauchen", "grinsen", "herkommen(i)", "klopfen", "mangeln", "versetzen", "rollen", "zustimmen", "vereinen", "herausfinden(i)", "atmen", "qualifizieren", "überwinden", "vermögen", "aufbringen(i)", "zutreffen", "vorgehen(i)", "sich auswirken", "decken", "aufmachen", "bedrohen", "sich bewerben", "entnehmen", "bearbeiten", "eintreffen", "einsteigen", "erlernen", "rennen", "übergehen(i)", "verbleiben(i)", "vorziehen", "vollziehen", "verlängern", "vermissen", "verschließen(i)", "sich zuwenden", "zucken"
];

let germanVerbsList8 = [
    "aufkommen", "bewahren", "zusammenarbeiten", "abbrechen(i)", "dominieren", "gewährleisten", "einhalten", "einschalten", "küssen", "identifizieren", "klettern", "sich nähern", "streiten", "vorwerfen", "sich scheiden lassen", "zurückhalten", "ansteigen", "überschreiten", "versterben", "winken", "beklagen", "ausbreiten", "benennen", "zittern", "angreifen", "erlangen", "erwidern", "hinausgehen(i)", "markieren", "korrigieren", "losgehen(i)", "transportieren", "mitmachen", "verweigern", "schildern", "verwandeln", "widersprechen", "vorschreiben", "abholen", "aufsetzen", "ausgleichen", "absetzen", "andeuten", "aufbrechen(i)", "anbringen(i)", "etablieren", "flüstern", "einschlafen", "einleiten", "einigen", "gleiten", "pressen", "bevorstehen", "austauschen", "aufzeigen", "aussteigen", "fliehen(i)", "eingreifen", "entspannen", "putzen", "reinigen", "resultieren", "verdeutlichen", "anfallen(i)", "umgeben(i)", "wiegen", "anführen", "beauftragen", "ausbrechen(i)", "aushalten", "dringen", "eindringen", "einschließen(i)", "entfallen(i)", "kleben", "notieren", "reizen", "verlegen", "vertreiben", "verschaffen", "abhalten", "abstellen", "verringern", "sich bedanken", "zurücktreten", "besorgen", "biegen", "dastehen", "ausfüllen", "beibringen(i)", "befestigen", "beschleunigen", "haften", "erwischen", "erregen", "nachfolgen", "hocken", "nachgehen(i)", "übereinstimmen", "schleppen"
];

let germanVerbsList9 = [
    "verkünden", "vernichten", "vergrößern", "abbilden", "abdecken", "unterbringen(i)", "abzeichnen", "abspielen", "sich abspielen", "ablösen", "abweichen", "basieren", "entgegenkommen", "entwerfen", "isolieren", "schwingen", "ruhen", "tauchen", "verhandeln", "übersehen", "versagen", "verbrennen(i)", "verzeichnen", "verwirklichen", "verknüpfen", "anklagen", "aufklären", "bedauern", "backen(i)", "ausschalten", "befriedigen", "aufwachen", "auftragen", "ausscheiden", "auskommen", "einschätzen", "erschließen(i)", "bekämpfen", "beschädigen", "erziehen", "formen", "jagen", "kombinieren", "motivieren", "kriechen(i)", "lenken", "spazieren (gehen)", "reiten", "umbringen(i)", "wandeln", "verdanken", "untergehen(i)", "abziehen", "versammeln", "zusehen", "zusammenkommen", "ausstellen", "sich bewähren", "beinhalten", "aktivieren", "aufsuchen", "bewältigen", "berufen", "bereitstellen", "einreichen", "blühen", "einschlagen", "ertragen", "ersparen", "sich erstrecken", "erfreuen", "sich erholen", "gestehen", "erschießen(i)", "löschen", "konfrontieren", "infizieren", "schweben", "telefonieren", "veranlassen", "verhaften", "überstehen", "trösten", "strahlen", "verkehren", "unterschreiben", "weitergeben(i)", "zustehen", "vorangehen(i)", "weitermachen", "zulegen", "abheben", "agieren", "abschneiden", "aufrufen", "anrichten", "ausprobieren", "aufschreiben", "anordnen", "ausweichen"
];

let germanVerbsList10 = [
    "begehen(i)", "anstehen", "ausdehnen", "sich begeben(i)", "beseitigen", "beabsichtigen", "ausnutzen", "beeinträchtigen", "bergen", "dokumentieren", "demonstrieren", "einlassen", "charakterisieren", "erforschen", "erwecken", "fressen(i)", "erschöpfen", "flüchten", "erwachen", "gießen(i)", "erschweren", "hervorgehen(i)", "grüßen", "gleichen", "sich irren", "lauschen", "loswerden", "sicherstellen", "stehlen", "spiegeln", "überziehen", "umwandeln", "überwachen", "zurücklegen", "zusammenstellen", "zusagen", "abwenden", "aufschlagen", "ansiedeln", "aufbewahren", "beleben", "auswerten", "beschaffen", "einsehen", "entfalten", "erhoffen", "erleiden", "eilen", "freigeben(i)", "fixieren", "festnehmen", "hassen", "hinnehmen", "hervorrufen", "lagern", "klingeln", "rauschen", "plädieren", "rutschen", "regnen", "umarmen", "spezialisieren", "strecken", "unterstreichen", "verschärfen", "verfallen(i)", "vermindern", "vernehmen", "zurückgeben(i)", "auflegen", "auslegen", "brüllen", "einlegen", "durchziehen", "fotografieren", "gestatten", "erlassen", "hervorheben", "lügen", "sich schämen", "operieren", "strukturieren", "servieren", "verdrängen", "übertreiben", "unterdrücken", "vorlesen", "wehen", "verdoppeln", "zerreißen", "vereinfachen", "verwundern", "zuführen", "vorbeugen", "abreißen", "abschalten", "zielen", "anmerken", "ablenken", "zurückweisen"
];

let germanVerbsList11 = [
    "zutrauen", "ausnehmen", "beten", "bohren", "aufziehen", "sich benehmen", "braten(i)", "durchgehen(i)", "sich erkundigen", "dulden", "bremsen", "einholen", "loslassen", "konzipieren", "protestieren", "schreiten", "schimpfen", "repräsentieren", "spannen", "täuschen", "sich täuschen", "verfassen", "umstellen", "wegnehmen", "überfordern", "vertiefen", "zurückgreifen", "aufräumen", "angehören", "anvertrauen", "antun", "entgehen(i)", "herausgeben(i)", "festsetzen", "inszenieren", "mahnen", "schleichen", "reflektieren", "überholen", "trocknen", "segeln", "unterstellen", "streben", "vortragen", "vernachlässigen", "verbrauchen", "überfahren(i)", "stapeln", "renovieren", "einpacken", "aufladen(i)", "unterlassen", "konsumieren", "genehmigen", "sich ereignen", "platzen", "wärmen", "baden", "anspannen", "tauschen", "zweifeln", "fegen", "tanken", "kennenlernen", "verzeihen", "(sich) langweilen", "stechen", "abschreiben", "füttern", "sich beschweren", "tippen", "spenden", "(sich) ernähren", "spinnen", "anschaffen", "behindern", "frieren(i)", "umziehen", "heizen", "anklicken", "auspacken", "überweisen", "basteln", "schwanken", "spülen", "belohnen", "überreden", "pflanzen", "halbieren", "sich amüsieren", "ausruhen", "stinken", "nähen", "schlucken", "hüten", "ausleihen(i)", "spendieren", "surfen", "absagen", "siegen"
];

let germanVerbsList12 = [
    "feststehen", "(sich) vertragen", "blitzen", "zuschauen", "entsorgen", "gratulieren", "bereisen", "sich verabreden", "schaden", "vermieten", "einfügen", "übernachten", "verschenken", "mitspielen", "wackeln", "ernten", "abfahren(i)", "hinterfragen", "beleidigen", "pfeifen", "vorhersagen", "begraben", "betrügen", "untersagen", "einzahlen", "schminken", "meistern", "verwalten", "versäumen", "bestrafen", "impfen", "reservieren", "parken", "abonnieren", "streiken", "austragen", "verpacken", "schneien", "zubereiten", "überqueren", "gebrauchen", "sich umziehen", "dekorieren", "heilen", "(sich) färben", "bloggen", "alarmieren", "abbiegen", "zusammenhalten", "besichtigen", "vorbeikommen", "bekanntgeben(i)", "sich weigern", "kopieren", "umsteigen", "schwitzen", "mieten", "jubeln", "(he)runterladen(i)", "verwechseln", "einbrechen(i)", "verabreden", "schmerzen", "verstauen", "wetten", "beißen(i)", "verschreiben", "ausdrucken", "sich anstrengen", "klicken", "buchen", "berauben", "leihen(i)", "weiterhelfen", "aufhängen", "hauen", "schälen", "zaubern", "reparieren", "restaurieren", "drucken", "staunen", "sich wohlfühlen", "entgegnen", "urteilen", "schmücken", "klauen", "(sich) kreuzen", "herausfordern", "fesseln", "versenden", "plaudern", "heulen", "importieren", "exportieren", "sich verschlechtern", "graben(i)", "schmeißen", "erwirtschaften", "schwören"
];

let germanVerbsList13 = [
    "reiben", "meiden", "anfassen", "(sich) bekennen", "erben", "hinterlegen", "mitbekommen", "streicheln", "verwöhnen", "rasen", "anwachsen", "verderben", "loslegen", "befürworten", "bezweifeln", "respektieren", "stürmen", "entkommen", "besiegen", "verneinen", "bejahen", "schwächen", "generieren", "hereinkommen", "bedingen", "vorübergehen(i)", "differenzieren", "murmeln", "erstaunen", "weggehen(i)", "wiedersehen", "verwirren", "hinfahren(i)", "verzweifeln", "zusammenleben", "aufspringen", "seufzen", "aufreißen", "aufrichten", "herausnehmen", "abgrenzen", "vorherrschen", "vorbeigehen(i)", "anstarren", "duzen", "abfliegen(i)", "wehtun", "schnarchen", "grillen", "fernsehen", "sich rasieren", "nachforschen", "einchecken", "faulenzen", "kaputtgehen(i)", "bluten", "verpflegen", "zurechtkommen", "wiederkommen", "(he)runterfahren(i)", "zelten", "anmachen", "zanken", "losfahren(i)", "chatten", "weglaufen", "frösteln", "duschen", "verbrechen(i)", "sich weiterbilden", "schielen", "sich beeilen", "abtrocknen", "weben", "drankommen", "donnern", "wegfahren(i)", "kaputtmachen", "eincremen", "sprudeln", "(sich) näherkommen", "pusten", "geizen", "verreisen", "husten", "zurückfahren(i)", "hochladen(i)", "stehenbleiben(i)", "frühstücken", "vorzeigen", "dazugeben(i)", "hageln", "nachschlagen", "verprassen", "Rad fahren(i)", "abmachen", "einschenken", "anhaben", "niesen", "umtauschen"
];

let germanVerbsList14 = [
    "sich vergnügen", "abwaschen", "wegwerfen", "wegmachen", "kauen", "misstrauen", "kitzeln", "prasseln", "verheimlichen", "hupen", "missverstehen", "einleuchten", "mitkommen", "zumachen", "föhnen", "wegbringen(i)", "aufessen(i)", "labern", "verschmutzen", "abschleppen", "gähnen", "ankreuzen", "buchstabieren", "lackieren", "ausrollen", "anschnallen", "sich erkälten", "joggen", "schmieren", "kämmen", "hämmern", "bürsten", "salzen", "sich verspäten", "schmollen", "nachschauen", "leichtfallen(i)", "mogeln", "anlügen(i)", "hinsetzen", "beunruhigen", "verhungern", "adoptieren", "zuschicken", "zusenden(i)", "jonglieren", "einatmen", "ausatmen", "knurren", "bellen", "dabeihaben", "misslingen", "überfallen(i)", "kneifen", "zwicken", "abhauen", "saufen", "anprobieren", "applaudieren", "fasten", "betteln", "hochfahren(i)", "zurücksetzen", "bügeln", "aussterben", "abschweifen", "leidtun", "popeln", "siezen", "satthaben", "zurücklaufen", "anspitzen", "sich schnäuzen", "staubsaugen", "hinunterwerfen", "verwelken", "schimmeln", "radieren"
];