export {
    germanNounsList1, germanNounsList2, germanNounsList3, germanNounsList4, germanNounsList5, germanNounsList6,
    germanNounsList7, germanNounsList8, germanNounsList9, germanNounsList10, germanNounsList11, germanNounsList12,germanNounsList13, germanNounsList14, germanNounsList15, germanNounsList16, germanNounsList17, germanNounsList18, germanNounsList19, germanNounsList20, germanNounsList21, germanNounsList22, germanNounsList23, germanNounsList24, germanNounsList25, germanNounsList26, germanNounsList27, germanNounsList28, germanNounsList29, germanNounsList30
};

let germanNounsList1 = [
    "die Uhr", "das Jahr", "der, die, das Erste", "der Euro", "der Mensch", "das Kind", "der Tag", "die Stadt", "die Zeit", "das Prozent", "das Foto", "die Frau", "die Woche", "das Ende", "der Mann", "der Sonntag", "das Land", "das Deutschland", "das Haus", "der Platz", "das Spiel", "die Million, Mio.", "der Fall", "das Leben", "das Bild", "das Thema", "der Monat", "die Frage", "die Arbeit", "die Minute", "die Schule", "der Teil", "das Teil", "die Seite", "das Unternehmen", "das Mal", "die Welt", "der Grund", "das Problem", "das Beispiel", "das Wort", "die Art", "die Sache", "der Bereich", "der Weg", "das Geld", "die Geschichte", "die Stunde", "der Name", "das Paar", "der Kopf", "die Gesellschaft", "die Leute", "die Stelle", "die Möglichkeit", "die Form", "das Wasser", "das Buch", "der Abend", "die Entwicklung", "der Morgen", "die Hand", "der Sinn", "die Familie", "die Aufgabe", "die Universität, Uni", "die Person", "das Ziel", "der Staat", "der Freund", "das Ding", "der Raum", "die Nacht", "die Eltern", "das System", "der Blick", "der Herr", "die Zahl", "die Straße", "das Gesicht", "die Sprache", "der Wert", "die Gruppe", "der Anfang", "der Moment", "der Ort", "das Recht", "das Interesse", "die Folge", "die Milliarde, Mrd.", "der Text", "das Ergebnis", "die Bedeutung", "der Schüler", "die Rolle", "die Tür", "der Krieg", "das Gespräch", "das Stück", "der Punkt", "die Weise"
];

let germanNounsList2 = [
    "die Regierung", "die Situation", "die Wohnung", "der Meter", "der Preis", "der Lehrer", "der Begriff", "das Werk", "das Jahrhundert", "der Sohn", "der Boden", "die Funktion", "die Richtung", "der Rahmen", "die Stimme", "die Angst", "die Information", "die Musik", "die Kunst", "das Programm", "der Schritt", "die Politik", "der Beruf", "der Gott", "das Auto", "die Regel", "die Mutter", "die Zukunft", "der Tisch", "die Beziehung", "die Erfahrung", "die Bank", "die Partei", "die Tochter", "das Gefühl", "die Kirche", "das Licht", "der Präsident", "der Markt", "der Film", "das Verhältnis", "der Doktor, Dr.", "der Gedanke", "der Betrieb", "das Mädchen", "der Prozess", "die Entscheidung", "der Zusammenhang", "das Gesetz", "die Firma", "der September", "die Kraft", "der Student", "die Chance", "die Zeitung", "die Grenze", "das Internet", "der Erfolg", "der Satz", "das Angebot", "das Mitglied", "die Lage", "die Leistung", "die Kultur", "der Arzt", "das Zimmer", "der Fuß", "der Zug", "das Projekt", "der Chef", "das Verhalten", "die Höhe", "die Lösung", "der Körper", "das Fenster", "die Klasse", "der Junge", "die Idee", "das Produkt", "der Vergleich", "die Meinung", "die Luft", "das Studium", "das Mittel", "der Mitarbeiter", "der Kunde", "das Bett", "das Modell", "die Natur", "der Tod", "die Bewegung", "der Spaß", "das Geschäft", "die Wirtschaft", "das Tier", "das Dorf", "der Einsatz", "die Sicherheit", "der Dank", "das Gebiet"
];

let germanNounsList3 = [
    "der Gast", "die Angabe", "der Bruder", "der Kollege", "die Menge", "der Kontakt", "der Sommer", "das Herz", "die Verfügung", "die Antwort", "die Verbindung", "der Anspruch", "die Anwendung", "der Unterschied", "das Alter", "die Kosten", "die Vorstellung", "die Ausbildung", "der Patient", "die Polizei", "das Theater", "das Gerät", "die Gefahr", "die Hilfe", "der Vater", "der Computer", "das Verfahren", "der Kilometer, km", "die Maßnahme", "die Ordnung", "der Stoff", "der Vertrag", "der Beginn", "die Mitte", "das Wochenende", "die Reihe", "der Oktober", "der Westen", "das Glück", "der Professor", "der Osten", "das Institut", "die Ebene", "die Bevölkerung", "die Schwester", "die Einheit", "das Haar", "die Erde", "das Prinzip", "die Reise", "der Vorteil", "die Bedingung", "die Nähe", "der Autor", "der Montag", "die Struktur", "der Brief", "das Risiko", "die Wahl", "die Medien", "die Größe", "die Wirkung", "die Methode", "die Macht", "die Veränderung", "die Untersuchung", "die Organisation", "der Einfluss", "die Daten", "die Rede", "die Liebe", "der Kreis", "die Diskussion", "der Sport", "die Forderung", "die Krankheit", "der Versuch", "die Technik", "der Kampf", "die Tätigkeit", "die Voraussetzung", "der Eindruck", "die Reaktion", "der Künstler", "die Region", "das Konzept", "der Beitrag", "der Artikel", "der Wunsch", "die Linie", "der Rücken", "die Aussage", "der Bürger", "der Gegensatz", "der Inhalt", "der Himmel", "der Jugendliche", "die Wand", "die Farbe", "das Maß"
];

let germanNounsList4 = [
    "das Bein", "der Aspekt", "das Papier", "die Sonne", "der Umstand", "die Kenntnis", "die Sekunde", "die Erinnerung", "die Küche", "der Kurs", "der Druck", "der Garten", "die Wissenschaft", "die Grundlage", "die Hälfte", "der Dienst", "das Essen", "der Plan", "der Zustand", "das Meer", "der Gegenstand", "der Auftrag", "das Auge", "die Freude", "der Hinweis", "der Zeitpunkt", "der Baum", "der November", "die Gemeinde", "das Netz", "der Schluss", "die Forschung", "die Haut", "die Position", "der Ausdruck", "die Praxis", "der Dienstag", "die Freundin", "das Russisch", "das Glas", "die Sicht", "der Wald", "die Maschine", "die Nummer", "die Umwelt", "der Politiker", "der Roman", "das Team", "der Hund", "der Haushalt", "der Titel", "der Verein", "das Fernsehen", "die Unterstützung", "die Ruhe", "der Schaden", "der Soldat", "die Umgebung", "die Produktion", "das Zeichen", "der Wind", "die Tatsache", "der Rest", "das Material", "das Volk", "der Zweck", "die Sorge", "der Wagen", "der Angriff", "die Öffentlichkeit", "der Job", "der Schutz", "der Anteil", "der Beschäftigte", "der Antrag", "der Grad", "der Gang", "der Mittwoch", "der Lauf", "die Erklärung", "die Energie", "der Besuch", "das Amt", "das Ausland", "das Zentrum", "das Hotel", "die Studie", "das Feld", "die Einrichtung", "die Behandlung", "die Hochschule", "das Publikum", "der Vorsitzende", "der Berg", "die Erkenntnis", "die Spur", "der Fehler", "der Partner", "der See", "die See"
];

let germanNounsList5 = [
    "die Freiheit", "die Kritik", "das Ereignis", "die GmbH", "der Sprecher", "das Objekt", "die Kontrolle", "die Fähigkeit", "das Opfer", "der Arbeitsplatz", "die Wahrheit", "die Verantwortung", "der Urlaub", "die Aufnahme", "die Karte", "der Norden", "das Schiff", "das Jahrzehnt", "die Ausstellung", "das Gebäude", "die Prüfung", "die Regelung", "die Hoffnung", "der Bezug", "die Bitte", "der Bericht", "das Gericht", "der Gewinn", "der König", "der Mai", "das Band", "der Band", "die Band", "die Einstellung", "die Union", "die Tat", "der Besucher", "der Bund", "der Sieg", "der Traum", "die Qualität", "der Rand", "der Hintergrund", "der Freitag", "der Bauer", "der Verlust", "die Vergangenheit", "die Ursache", "der Zuschauer", "die Anzahl", "der Winter", "der Samstag", "das Instrument", "der Vertreter", "die Nachricht", "die Bildung", "die Insel", "der Januar", "der Abstand", "die Generation", "der Vorschlag", "die Pflanze", "der Leiter", "die Leiter", "der Dezember", "das Blatt", "der Abschluss", "das Interview", "der Donnerstag", "der Geist", "der Stand", "das Element", "der Hof", "die Kommunikation", "die Tradition", "die Dame", "die Bühne", "die Gelegenheit", "die Anlage", "die Behörde", "das Museum", "die Basis", "die Ecke", "die Nutzung", "die Zusammenarbeit", "der Herbst", "das Verständnis", "der Bürgermeister", "die Bahn", "die Nation", "der Stein", "die Ansicht", "der Ton", "die Phase", "die Änderung", "der Konflikt", "der Kaffee", "der Bau", "die Veranstaltung", "die Rechnung"
];

let germanNounsList6 = [
    "die Ausnahme", "der Nachmittag", "die Mehrheit", "die Leitung", "das Fest", "die Aktivität", "die Lust", "die Landschaft", "die Mannschaft", "das Schloss", "das Dach", "der Kandidat", "die Runde", "der Stern", "der Experte", "der Laden", "der Meister", "der Frieden", "die Figur", "die Industrie", "der Zugang", "die Branche", "das Wachstum", "der Umgang", "der Fußball", "das Lager", "das Pferd", "das Büro", "der Rat", "die Szene", "die Gewalt", "der Konzern", "die Dauer", "das Feuer", "die Spitze", "die Strecke", "das Gymnasium", "die Aktie", "das Tor", "der Juli", "die Konsequenz", "der Anlass", "die Aktion", "der Club", "der Verband", "das Gut", "der Fluss", "die Ausgabe", "der Nachbar", "das Bundesland", "die Führung", "die Software", "der Zweifel", "das Telefon", "der Trainer", "der Bus", "das Bad", "die Messe", "die Anforderung", "die Kommission", "das Krankenhaus", "der Richter", "der Anbieter", "das Urteil", "die Jugend", "die Schuld", "der Juni", "der Wein", "die Stimmung", "das Wetter", "der Wettbewerb", "die Alternative", "die Tasche", "die Auswirkung", "der Leser", "die Waffe", "die Temperatur", "die Fahrt", "die Förderung", "die Ware", "die Koalition", "die Einführung", "der Spieler", "der Manager", "der Test", "die Summe", "der Regen", "die Quelle", "der Strom", "das Vertrauen", "der Termin", "der Vorwurf", "der Umsatz", "der April", "die Bundesregierung", "das Bier", "der Wissenschaftler", "die Krise", "das Konzert", "das Parlament"
];

let germanNounsList7 = [
    "der März", "das Lied", "die Pause", "die Suche", "der Aufbau", "der August", "der Weltkrieg", "die Botschaft", "der Arbeitgeber", "die Hauptstadt", "die Nachfrage", "die Pflicht", "der Geburtstag", "der Teilnehmer", "die Debatte", "der Gegner", "die Verwaltung", "die Adresse", "die Heimat", "der Betrag", "das Kino", "die Konkurrenz", "der Schwerpunkt", "der Streit", "der Kauf", "der Erwachsene", "die Verhandlung", "das Drittel", "der Arbeitnehmer", "der Fahrer", "die Gemeinschaft", "das Gegenteil", "der Sitz", "der Start", "die Gewerkschaft", "der Handel", "der Minister", "der Vogel", "der Widerstand", "der Bundestag", "der Beamte", "die Investition", "das Steuer", "die Steuer", "die Planung", "die Stärke", "der Polizist", "der Abgeordnete", "der Anschluss", "der Verkehr", "die Auswahl", "die Verletzung", "die Fläche", "die Gesundheit", "die Atmosphäre", "die Post", "die Einnahme", "das Bewusstsein", "der Wechsel", "die Saison", "der Flughafen", "der Park", "der Bahnhof", "die Demokratie", "der Auftritt", "das Fahrzeug", "der Alltag", "der Hersteller", "die Erwartung", "der Pfarrer", "das Niveau", "der Zeitraum", "das Holz", "die Liste", "die Kombination", "die Abteilung", "der Verlag", "der Standort", "das Detail", "der Beweis", "der Forscher", "die Kasse", "die Kategorie", "die Verbesserung", "der Bedarf", "der Unfall", "die Beratung", "der Februar", "das Frühjahr", "das Gewicht", "der Journalist", "der Mittelpunkt", "der Spiegel", "die Bewertung", "die Brücke", "der Geschäftsführer", "die Beteiligung", "der Ruf", "der Standard", "die Vorbereitung"
];

let germanNounsList8 = [
    "die Initiative", "der Anwalt", "das Rennen", "das Seminar", "der Schuh", "das Vorjahr", "der Verbraucher", "der Verkauf", "die Truppe", "die Bilanz", "die Karriere", "das Grundstück", "die Kamera", "das Quartal", "das Rad", "das TV", "der Charakter", "der Bewohner", "die Niederlage", "die Halle", "die Herausforderung", "die Sitzung", "die Reform", "das Restaurant", "der Schauspieler", "der Vorstand", "die Zustimmung", "der Angehörige", "die Fraktion", "der Händler", "das Training", "das Motiv", "der Musiker", "die Station", "das Personal", "die Umsetzung", "das Wunder", "die Begründung", "die Auskunft", "das Engagement", "die Seele", "der Unternehmer", "die Not", "das Video", "die Vereinbarung", "das Café", "die Begegnung", "der Trend", "der Keller", "die Tonne", "die Variante", "der Rang", "der Regisseur", "die Republik", "der Stil", "das Handy", "der Fan", "die Kooperation", "der Einwohner", "der Täter", "die Tour", "der Beschluss", "die Börse", "der Flüchtling", "der Kindergarten", "der Stress", "der Ball", "die Aussicht", "das Geschenk", "der Höhepunkt", "das Kreuz", "der Vortrag", "der Ring", "das Gold", "die Klage", "die Marke", "die Klinik", "der Pass", "das Weihnachten", "die Serie", "die Umfrage", "die Note", "der Nachfolger", "der Protest", "der Schuss", "der Sieger", "das Turnier", "die Ermittlung", "das Japanisch", "der Saal", "das Motto", "der Quadratmeter, m²", "der Nutzer", "die Überraschung", "das Vorhaben", "die Werbung", "die Anzeige", "die Meldung", "die Schulden", "der Tipp"
];

let germanNounsList9 = [
    "das Stadion", "der Zeuge", "die Beschwerde", "die Bundesliga", "das Gelände", "der Lohn", "die Partie", "die Stiftung", "das Rathaus", "die Show", "die Version", "die Anfrage", "die Auflage", "der Wähler", "der Ausbau", "der Landkreis", "der Investor", "die Plattform", "die Pflege", "der Rock", "der Tanz", "der Ausgleich", "der Bezirk", "die Empfehlung", "die Eröffnung", "der Senat", "die Teilnahme", "das Festival", "die Grundschule", "die Galerie", "die Innenstadt", "der Liter", "das Netzwerk", "die Feuerwehr", "der Helfer", "die Party", "die Liga", "der Chor", "das Design", "der Eintritt", "der Kommentar", "der Parkplatz", "das Forum", "der Sänger", "der Veranstalter", "der Gemeinderat", "die Kommune", "der Gruß", "der Koch", "das Profil", "die Mark", "der Hamburger", "das China", "das Frankreich", "der Genuss", "das Schreiben", "das England", "der Service", "das Österreich", "das Türkei", "die E-Mail, Email", "das Russland", "die Website", "das Großbritannien", "die Schweiz", "das Japan", "die Homepage", "die Garantie", "die Spende", "das Spanien", "der Blog", "das Nein", "der Link", "der Brand", "der Treffpunkt", "der Senior", "das Fax", "der Sonnabend", "der Deutsche", "das Polen", "das Italien", "der Star", "das München", "das Wissen", "die Anmeldung", "das Amerika", "der Autofahrer", "der Tote", "das Schweden", "das Los", "das Europa", "der Aufzug", "der Bach", "das Treffen", "das Köln", "das Bayern", "das Deutsch", "die Schülerin", "die Lehrerin", "die Abbildung, Abb."
];

let germanNounsList10 = [
    "der Absatz, Abs.", "der Arm", "das Zuhause", "die Studentin", "das Pro", "die Ärztin", "das Auftreten", "das Englisch", "das Französisch", "die Kundin", "die Kollegin", "das Fach", "die Patientin", "das Lächeln", "die Autorin", "der Augenblick", "die Schwierigkeit", "die Künstlerin", "der Mund", "das Kapitel", "die Bürgerin", "die Literatur", "die Zelle", "die Bibliothek", "der Ansatz", "die Wirklichkeit", "die Bundesrepublik", "der Finger", "die Politikerin", "die Theorie", "die Schulter", "der Anschlag", "der Unterricht", "die Analyse", "die Freizeit", "die Gegend", "der Faktor", "die Partnerin", "der Typ", "das Ohr", "der Gesellschafter", "der Amerikaner", "der Direktor", "die Direktorin", "die Aktiengesellschaft, AG", "der Abschnitt", "die Ehe", "die Störung", "der Zentimeter, cm", "die Eigenschaft", "das Semester", "die Mama", "das Kriterium", "der Jude", "der Terror", "die Definition", "die Auseinandersetzung", "das Flugzeug", "die Masse", "das Hobby", "das Italienisch", "die Mauer", "die Gestalt", "die Stellung", "der Vorgang", "die Institution", "die Darstellung", "der Schatten", "die Lehre", "die Katze", "das Blut", "die Weltmeisterschaft, WM", "der Süden", "der Ausländer", "die Nase", "der Stuhl", "die Nachbarin", "die Geschwindigkeit", "die Stufe", "die Medizin", "der Terrorismus", "der Umfang", "die Belastung", "der Effekt", "die Vorschrift", "der Mangel", "die Richterin", "das Fahrrad", "der Terrorist", "die Decke", "der Schmerz", "das Fleisch", "der Fisch", "die Welle", "das Bedürfnis", "die Haltung", "die Tante", "die Ahnung", "die Brust", "die Länge"
];

let germanNounsList11 = [
    "die Religion", "das Loch", "das Kleid", "der Tourist", "die Verwendung", "das Merkmal", "das Leid", "die Landwirtschaft", "das Phänomen", "die Perspektive", "die Realität", "das Brot", "die Formel", "die Gegenwart", "die Bestimmung", "der Fortschritt", "die Flasche", "der Studiengang", "der Wille", "die Mühe", "die Fremdsprache", "das Kilogramm, kg", "die Hinsicht", "der Käufer", "die Weile", "die Mathematik", "der Hals", "die Schicht", "der Ablauf", "der Kanzler", "der Nachteil", "die Platte", "der Millimeter, mm", "die Tabelle", "das Management", "das Spanisch", "der Verdacht", "der Tourismus", "der Schriftsteller", "die Schriftstellerin", "die Therapie", "die Armee", "die Überlegung", "die Erkrankung", "die Beschreibung", "die Stirn", "das Boot", "die Physik", "das Gehirn", "die Strategie", "der Bundeskanzler", "die Fotografie", "das Schicksal", "das Knie", "die Schrift", "die Dimension", "das Aids", "der Organismus", "die Integration", "das Abitur", "das Radio", "die Beschäftigung", "die Verpflichtung", "die Betrachtung", "die Journalistin", "das Lebensmittel", "die Kompetenz", "das Vermögen", "der Strand", "die Treppe", "die Bezeichnung", "der Bestandteil", "das Wesen", "der Gebrauch", "die Arbeitslosigkeit", "die Beobachtung", "die CD", "der Russe", "die Taste", "die Versicherung", "der Nutzen", "die Lippe", "das Signal", "der Vordergrund", "die Substanz", "die Komponente", "das Experiment", "der Grundsatz", "die Oberfläche", "der Schlag", "der Glaube", "die Sendung", "die Technologie", "das Reich", "das Umfeld", "die Spannung", "das Viertel", "die Identität", "der Kanal", "das Erlebnis"
];

let germanNounsList12 = [
    "das Plus", "der Sender", "die Tiefe", "der Verlauf", "der Kredit", "der Aktionär", "der Rechner", "der Schlaf", "das Tal", "das Einkommen", "die Zigarette", "die Auffassung", "der Atem", "die Geburt", "der Mittag", "die Erziehung", "die Norm", "der Sturm", "die Trauer", "der Schnee", "die Träne", "das Argument", "der Zufall", "der Bescheid", "die Bundeswehr", "das Arzneimittel", "der Außenminister", "die Annahme", "die Existenz", "der Benutzer", "die Blume", "die Disziplin", "das Individuum", "die Katastrophe", "der Hinblick", "das Grundgesetz", "der Papa", "der Sand", "die Opposition", "die Tendenz", "die Versorgung", "der Verkäufer", "die Verkäuferin", "der Wandel", "das Ausmaß", "die Angelegenheit", "der Fleck", "der Koffer", "das Immunsystem", "die Handlung", "die Entfernung", "die Persönlichkeit", "der Schreibtisch", "die Unternehmung", "der Schlüssel", "die Wahrnehmung", "der Angestellte", "die Dienstleistung", "die Äußerung", "die Erzählung", "die Datei", "die Ferne", "das Konto", "die Operation", "das Gedicht", "die Sammlung", "die Gründung", "die Qualifikation", "die Vielfalt", "der Träger", "die Zahlung", "die Vielzahl", "der Verwandte", "die Aufwendung", "der Arbeiter", "der Bauch", "der Aufwand", "der Bestand", "der Entwurf", "die Berechnung", "das Entwicklungsland", "die Fachhochschule", "die Hose", "der Fernseher", "das Kapital", "der Kern", "die Finanzierung", "der Motor", "der Impuls", "der Wahlkampf", "das Salz", "die Anstrengung", "die Behinderung", "die Vermittlung", "die Wolke", "der Zahn", "die Hütte", "der Eingriff", "die Berücksichtigung", "der Dichter"
];

let germanNounsList13 = [
    "die Trennung", "die Verfassung", "das Symbol", "die Übertragung", "der Architekt", "die Aufmerksamkeit", "die Zeitschrift", "die Absicht", "die Bindung", "die Einschätzung", "die Bibel", "die Entstehung", "die Flucht", "die Erweiterung", "das Business", "der Ehegatte", "das Gewissen", "das Hemd", "der Halt", "der Griff", "das Geschlecht", "der Feind", "der Gläubiger", "der Mut", "die Oper", "die Infektion", "das Orchester", "das Marketing", "das Klima", "der Kontinent", "das Paket", "die Kündigung", "der Mantel", "die Nebenwirkung", "die Richtlinie", "die Scheibe", "die These", "die Ressource", "der Übergang", "die Rückkehr", "der Transport", "die Revolution", "die Stille", "das Vorgehen", "der Widerspruch", "das Vorbild", "der Alkohol", "der Aufenthalt", "die Wüste", "der Besitz", "die Anerkennung", "die Bemerkung", "die Chemie", "das Ei", "das Heim", "die Frist", "die Distanz", "der Horizont", "die Konferenz", "die Gestaltung", "die Presse", "die Recht(s)sprechung", "das Organ", "das Regal", "die Notwendigkeit", "die Übung", "die Zeile", "die Ausführung", "die Erscheinung", "der Besitzer", "der Flug", "die Ferien", "das Center", "die Freundschaft", "der Eingang", "das Geräusch", "der Hafen", "die Fragestellung", "das Gehalt", "der Gehalt", "das Geheimnis", "das Frühstück", "die Miete", "der Geschmack", "das Medikament", "das Öl", "die Hut", "der Hut", "die Interpretation", "das Protein", "der Tee", "die Überzeugung", "das Protokoll", "die Fantasie, Phantasie", "die Prognose", "die Vorgabe", "der Turm", "die Wende", "die Abhängigkeit", "die Betreuung"
];

let germanNounsList14 = [
    "der Arbeitsmarkt", "der Dialog", "der Ärger", "die Bombe", "der Austausch", "das Gas", "die Erhöhung", "die Entschuldigung", "das Klavier", "die Kindheit", "die Hitze", "das Gen", "der Leib", "der Maler", "die Malerin", "die Menschheit", "die Konzentration", "der Riese", "der Pilot", "die Milch", "der Mord", "der Übersetzer", "das Ufer", "der Stock", "die Strafe", "das Resultat", "das Baby", "die Differenz", "die Dunkelheit", "das Eis", "die City", "der Empfang", "das Dutzend", "der Empfänger", "die Großmutter", "der Franzose", "die Ernährung", "die Konjunktur", "die Herkunft", "der Konkurrent", "der Hunger", "die Hochzeit", "der Gesichtspunkt", "das Lebensjahr", "die Mischung", "der Onkel", "die Last", "das Medium", "der Rohstoff", "das Muster", "das Potenzial", "die Statistik", "der Reiz", "die Sicherung", "die Übernahme", "die Verarbeitung", "der Sachverhalt", "das Taxi", "die Strahlung", "die Verteilung", "der Abschied", "die Veröffentlichung", "die Wiedervereinigung", "der Witz", "die Beurteilung", "die Benutzung", "die Einschränkung", "der Christ", "das Defizit", "das Format", "der Bewerber", "der Held", "der Flur", "die Kammer", "der Ertrag", "die Kleidung", "die Herstellung", "der Kritiker", "der Kaiser", "die Kneipe", "die Messung", "das Messer", "die Kette", "die Küste", "der Passagier", "der Moslem", "die Probe", "der Sektor", "die Premiere", "die Schwäche", "das Tuch", "das Tennis", "die Verbreitung", "der Sprung", "die Übersetzung", "das Top", "das Symptom", "die Wärme", "das Zelt", "der Anhänger"
];

let germanNounsList15 = [
    "die Vorlage", "der Virus", "die Aufklärung", "die Wiese", "die Bestellung", "das Bündnis", "die Burg", "die Auflösung", "der Dialekt", "der Bube", "die Einsicht", "die Geste", "die Durchführung", "die Infrastruktur", "die Herrschaft", "die Einigung", "die Mission", "das Gefängnis", "die Mitteilung", "das Gedächtnis", "die Oma", "der Katalog", "die Realisierung", "der Offizier", "die Philosophie", "die Nahrung", "der Nebel", "der Skandal", "die Sehnsucht", "der Schein", "die Schnittstelle", "der Schnitt", "die Wunde", "die Wurzel", "das Wiedersehen", "der Anstieg", "das Zeugnis", "die Bereitschaft", "der Befehl", "das Celsius", "die Anpassung", "der Anblick", "das Anliegen", "das Arbeitsamt", "der Bogen", "der Erreger", "die Feststellung", "die Epoche", "der Einzelfall", "die Formulierung", "die Droge", "die Ehre", "das Eigentum", "das Geschwister", "die Inszenierung", "der Kapitän", "der Kontext", "die Geliebte", "der Knochen", "das Gramm", "die Kiste", "der Lastkraftwagen, LKW", "der Magen", "der Mörder", "das Kunstwerk", "das Lebewesen", "die Mode", "die Reflexion", "die Rente", "die Öffnung", "die Unterscheidung", "der Teller", "die Zone", "der Zettel", "die Aufführung", "der Abbau", "der Zins", "die Agentur", "die Akademie", "das Bedenken", "der Bär", "die Einzelheit", "das Dokument", "der Buchstabe", "der Finanzminister", "der Führer", "das Gleichgewicht", "die Erfüllung", "die Fusion", "der Geruch", "das Labor", "der Komponist", "die Kurve", "der Kerl", "das Märchen", "die Moderne", "das Mittelalter", "das Möbel", "das Regime", "der Posten"
];

let germanNounsList16 = [
    "der Profi", "der Nerv", "der Ofen", "die Solidarität", "der Status", "der Schrank", "der Staub", "die Sekretärin", "der Überblick", "der Rücktritt", "der Sportler", "die Stabilität", "der Winkel", "der Vorhang", "der Topf", "die Unsicherheit", "das Zitat", "der Akteur", "die Begeisterung", "die Abgrenzung", "die Armut", "das Abenteuer", "die Allianz", "der Akt", "die Diagnose", "das Chinesisch", "die Einladung", "der Durchmesser", "das Dunkel", "der Friedhof", "das Fräulein", "die Front", "das Geschäftsjahr", "der Felsen", "der Hang", "die Flüssigkeit", "die Großstadt", "die Fülle", "das Gras", "der Kongress", "der Ingenieur", "der Hügel", "der Muskel", "das Polnisch", "der Nachweis", "die Rücksicht", "die Orientierung", "der Rhythmus", "das Universum", "die Unterhaltung", "der Stolz", "die Steuerung", "die Volkshochschule", "die Vereinigung", "die Wahrscheinlichkeit", "die Unterlage", "die Zeichnung", "die Vertretung", "das Werkzeug", "die Vorsicht", "die Wange", "die Zwiebel", "die Zunahme", "die Ablehnung", "die Anordnung", "die Anregung", "die Abstimmung", "der Aufsatz", "der Backofen", "die Bemühung", "die Bakterie", "der Bildschirm", "der Befund", "der Beobachter", "der Betrachter", "die Blüte", "der Berater", "das Betriebssystem", "der Eigentümer", "die Eintragung", "die Brille", "die Datenverarbeitung, DV", "das Ensemble", "die Enttäuschung", "das Gemüse", "die Faust", "der Großvater", "die Genehmigung", "der Konsument", "das Kloster", "der Hass", "die Höhle", "das Lokal", "die Münze", "der Lärm", "die Kohle", "die Malerei", "der Maßstab", "die Materie", "der Sack"
];

let germanNounsList17 = [
    "der Rückgang", "die Sportart", "der Schuldner", "das Praktikum", "der Teufel", "der Teppich", "die Tasse", "der Streifen", "der Stamm", "das Verbot", "die Vermutung", "die Versammlung", "die Wirtschaftspolitik", "die Überprüfung", "das Zeug", "der Unsinn", "die Wäsche", "die Zunge", "die Werkstatt", "der Zwang", "das Antibiotikum", "der Ausgang", "der Ausflug", "die Ausstattung", "die Anweisung", "die Architektur", "der Anzug", "die Breite", "der Aufstieg", "die Butter", "die Biologie", "der Dirigent", "der Betracht", "die Bearbeitung", "die Besonderheit", "der Champion", "die Entdeckung", "die Erfindung", "die Fluggesellschaft", "das Fieber", "die Gebühr", "der Ersatz", "der Generalsekretär", "der Grenzwert", "das Handwerk", "der Gesetzgeber", "das Gerücht", "das Heft", "der Geheimdienst", "das Gepäck", "der Jäger", "das Grab", "die Kartoffel", "die Königin", "der Kompromiss", "die Konstruktion", "die Intelligenz", "der Käse", "der Klang", "die Kugel", "der Kreislauf", "die Leiche", "die Kuh", "die Lieferung", "die Leidenschaft", "der Parteitag", "der Nachwuchs", "der Nacken", "das Milligramm", "die Leistungsfähigkeit", "die Problematik", "die Rezession", "der Planet", "der Priester", "die Schwangerschaft", "die Schauspielerin", "der Salon", "der Schweiß", "die Tafel", "das Tagebuch", "das Spektrum", "die Unruhe", "das Talent", "die Spalte", "die Steckdose", "der Ursprung", "das Tempo", "die Unterschrift", "die Verhaltensweise", "der Vermieter", "die Verordnung", "die Vernunft", "das Verbrechen", "das Vergnügen", "die Zusammensetzung", "die Achse", "der Vormittag", "die Villa", "das Wohnzimmer", "der Zinssatz"
];

let germanNounsList18 = [
    "die Zerstörung", "die Zulassung", "die Abschreibung", "die Anwesenheit", "die Aufregung", "der Durchschnitt", "das Chaos", "der Chip", "die Autobahn", "die Batterie", "die Fabrik", "der Einbruch", "das Ehepaar", "die Erholung", "das Getränk", "der Graf", "der General", "der Europäer", "die Furcht", "das Glied", "das Gewehr", "die Geduld", "die Haustür", "der Kasten", "das Gutachten", "die Gunst", "das Gremium", "der Italiener", "der Innenminister", "der Handwerker", "der Mieter", "das Menschenrecht", "die Kreativität", "das Magazin", "das Ministerium", "die Konzeption", "die Minderheit", "der Marktanteil", "das Militär", "die Maus", "das Präparat", "die Partnerschaft", "der Mythos", "die Säule", "die Periode", "die Naturwissenschaft", "der Regierungschef", "die Provinz", "die Schönheit", "die Rahmenbedingung", "die Scheidung", "der Spezialist", "der Stellvertreter", "die Steigerung", "die Subvention", "das Ticket", "das Unrecht", "die Uniform", "die Übersicht", "die Volkswirtschaft", "der Tunnel", "die Vorlesung", "das Vitamin", "die Weiterbildung", "der Zucker", "die Zielsetzung", "die Arbeitskraft", "der Apfel", "das Abkommen", "die Abwehr", "der Absolvent", "die Auswertung", "die Bekämpfung", "der Assistent, Assi", "das Darlehen", "die Bar", "die Bedrohung", "der Block", "die Beschränkung", "das Datum", "die Fachleute", "die Erhaltung", "der Erzähler", "die Gerechtigkeit", "die Frequenz", "der Gipfel", "der Fachbereich", "der Fakt", "der Flügel", "der Großteil", "die Fassung", "der Indianer", "die Frucht", "der Hörer", "die Jahreszeit", "die Linse", "die Jacke", "die Lücke", "die Motivation", "der Missbrauch"    
];

let germanNounsList19 = [
    "die Jagd", "die Lampe", "das Metall", "die Option", "die Pistole", "der Physiker", "der Ozean", "der Ordner", "der Respekt", "die Rose", "der Sozialdemokrat", "die Reparatur", "die Tageszeitung", "die Reichweite", "der Rucksack", "die Tablette", "die Verknüpfung", "der Umzug", "der Therapeut", "der Vorgänger", "der Weltmeister", "die Währung", "die Wut", "die Zuordnung", "die Akte", "der Zuwachs", "der Abfall", "der Aufsichtsrat", "der Araber", "der Ausweis", "die Ausrichtung", "die Anleihe", "der Einblick", "der Ausgangspunkt", "die Arbeitszeit", "der Frühling", "die Beachtung", "die Fakultät", "die Feier", "die Fassade", "der Engel", "die Erfassung", "die Fahne", "der Jurist", "der Kunststoff", "die Krankenkasse", "die Landesregierung", "das Gewebe", "die Kerze", "der Philosoph", "die Laune", "das Nahrungsmittel", "das Niederländisch", "der Prinz", "die Selb(st)ständigkeit", "die Schlange", "die Strömung", "der Spruch", "das Schwein", "der Strahl", "die Siedlung", "die Stellungnahme", "das Weib", "das Volumen", "die Verbindlichkeit", "der Zuhörer", "der Zugriff", "die Impfung", "das Festnetz", "die Pfanne", "die Speisekarte", "die Apotheke", "die Torte", "der Gewinner", "die Gratulation", "der Krebs", "die Sonnenbrille", "das Gasthaus", "das Pech", "die Besserung", "der Anruf", "der Kinderwagen", "der Elefant", "das Norwegen", "der Rundgang", "die Beere", "die Anreise", "der Führerschein", "der Daumen", "die Anleitung", "der Anfänger", "der Werktag", "das Spielzeug", "das T-Shirt", "der Zuschlag", "der Blödsinn", "die Tagesordnung", "das Porträt", "die Flöte", "die Erdbeere"
];

let germanNounsList20 = [
    "der Löwe", "der Import", "die Unterlagen", "die Rubrik", "der Ski", "der Wegweiser", "der Spaziergang", "die Zutat", "der Trick", "der Albtraum, Alptraum", "die Überstunde", "die Geldbörse", "die Allergie", "der Tierarzt", "der Studierende", "die Vermietung", "der Wohnsitz", "die Verwirrung", "der Dreck", "die U-Bahn", "der Konsum", "der Krimi", "die Reportage", "der Neffe", "der Umweg", "der Schmutz", "der Verrat", "das Insekt", "der Opa", "die Eile", "das Obst", "der Fahrplan", "die Rückmeldung", "der Feiertag", "das Gewitter", "die Lehrstelle", "der Stempel", "das Misstrauen", "der Tierpark", "die Gier", "die Schlägerei", "das Schlafzimmer", "der Pinguin", "die Postkarte", "das Indien", "die Blase", "die Tüte", "das Dessert", "das Fett", "der Zwilling", "die Rettung", "das Kissen", "der Alarm", "der Verdächtige", "der Betreuer", "die Sahne", "das Benzin", "die Wette", "die Mitternacht", "der Wurf", "die Überschrift", "die Achtung", "das Bargeld", "der Cent", "die Metropole", "der Pfleger", "das Versteck", "der Selbstmord", "die Einsamkeit", "der Stier", "das Abendessen", "der Reporter", "der Müll", "das Kochbuch", "das Erdgeschoss", "die Geschäftsleitung", "der Einbrecher", "der Kranke", "die Baustelle", "der Absender", "die Portion", "das Unglück", "das Kaufhaus", "die Hausaufgabe", "die Mücke", "der Lift", "der Notfall", "das Altenheim, Altersheim", "der Download", "der Zoll", "das Ballett", "die Biene", "der Terminkalender", "das Kraftfahrzeug", "der Knopf", "der Fasching", "das Verkehrsmittel", "das Fahrverbot", "der Supermarkt", "der Hauptbahnhof"
];

let germanNounsList21 = [
    "die Ehefrau", "die Chili", "die Belohnung", "die Hausfrau", "die Fortsetzung", "die Toilette", "der Pilz", "die Etage", "die Gitarre", "der Sekt", "der Becher", "die Vorwahl", "das Apartment", "die Pressekonferenz", "der Deckel", "die Einleitung", "der Bahnsteig", "das Passwort", "der Reifen", "der Streik", "der Fotograf", "die Personalie", "der Wohnort", "die Pizza", "das Fell", "der Lebenslauf", "die Visitenkarte", "die Unterkunft", "der Nagel", "das Modul", "das Rind", "die Null", "die Kriminalpolizei", "die Migration", "das Stipendium", "das Hilfsmittel", "die Folie", "der Auszubildende", "das E-Book", "die Krankenschwester", "das Reisebüro", "die Wolle", "die Urkunde", "die Schale", "die Broschüre", "die Hauptstraße", "die Einfahrt", "der Ehemann", "der Feierabend", "die Landung", "der Kakao", "das Ersatzteil", "die Papiere", "der Pfeffer", "der Bekannte", "die Couch", "die Süßigkeit", "der Apparat", "die Ziege", "der Mond", "der Betriebsrat", "die Ausfahrt", "die Neuigkeit", "das Pfund", "der Kellner", "die Recherche", "das Mobiltelefon", "das Stockwerk", "das Kanada", "der Wahnsinn", "das Referat", "das Schaufenster", "das Golf", "der Raucher", "die Suppe", "der Bauernhof", "der Kommissar", "die Sprechstunde", "die Abreise", "die Reihenfolge", "der Grill", "der Workshop", "die Anspannung", "das Portugal", "die Jungfrau", "die Garderobe", "die Billion", "der Schwan", "der Verlierer", "der Tropfen", "der Löffel", "die Festplatte", "das Jahrtausend", "der Vorname", "der Rück-", "der Migrant", "der Weihnachtsmarkt", "der Laptop", "der Ast", "die Bluse"
];

let germanNounsList22 = [
    "der Rettungsdienst", "die Müdigkeit", "die Disco, Disko(thek)", "das Tablet", "das Wiederhören", "der Notruf", "die Bewerbung", "die Kosmetik", "der Spitzname", "der Lieblings-", "das Ostern", "das Einkaufszentrum", "die Grafik", "der Zeigefinger", "der Flohmarkt", "der Imbiss", "der Volleyball", "der Affe", "die Klimaanlage", "die Hölle", "das Mittagessen", "die Kälte", "das Menü", "der Kofferraum", "das Pflaster", "der Kuss", "die Übereinstimmung", "der Verbrecher", "der Diebstahl", "das Poster", "die Abfahrt", "das Laster", "das Silber", "der Fußgänger", "der Radfahrer", "die Sauberkeit", "die Panik", "das Plakat", "das Kraut", "der Basketball", "die Fernbedienung", "die Wanderung", "die Pille", "der Ratschlag", "die Ansage", "der Moderator", "das Handtuch", "das Visum", "der Durst", "die Sorte", "die Rufnummer", "die Puppe", "das Neujahr", "die Erlaubnis", "das Kennzeichen", "die Fahrbahn", "die Viertelstunde", "die Fußgängerzone", "die Arbeitsstelle", "die Ostsee", "die Informatik", "der Dieb", "das Versäumnis", "die Schüssel", "der Verzicht", "der Export", "die Fortbildung", "die Seife", "der Glückwunsch", "das Afrika", "die Soße, Sauce", "die Umleitung", "die Verwandtschaft", "die Fähre", "der Geldbeutel", "die Waage", "die Buchung", "der Umweltschutz", "der Misserfolg", "der Schütze", "die Gaststätte", "der Laster", "die Sehenswürdigkeit", "der Rentner", "die Creme", "das Zertifikat", "die Nordsee", "das Silvester", "die Ernte", "die Spritze", "die Eisenbahn", "die Cafeteria", "die Verpackung", "die Verwechslung", "die Aussprache", "der Sportplatz", "die Mahlzeit", "das Schweigen", "der Kriminal-", "der Kalender"
];

let germanNounsList23 = [
    "das Geschirr", "das Südamerika", "der Arbeitstag", "die Garage", "das Rätsel", "der Betrüger", "die Ampel", "die Ausstrahlung", "die Schere", "der Lehrling", "die Krawatte", "das Model", "das Asyl", "der Golf", "der Zirkus", "das Mehl", "die Rundfahrt", "der Sarg", "die Frisur", "der Rasen", "der Beleg", "der Sozialarbeiter", "die Kreditkarte", "das Studio", "der Klick", "die Dose", "der Friseur, Frisör", "der Urlauber", "die Buchhandlung", "die Überweisung", "die Bremse", "die Klassik", "der Sessel", "das Plastik", "die Reservierung", "das Denkmal", "der Bart", "der Landwirt", "die Banane", "das Plätzchen", "die Zufriedenheit", "der Karneval", "die Marmelade", "das Monster", "die Ratte", "das Formular", "das Brötchen", "das Haustier", "der Hase", "das Umland", "das Leder", "die Ziffer", "die Teilzeit", "der Kaufmann", "das Sekretariat", "die Verpflegung", "der Stapel", "das Gleis", "die Warnung", "der Fachmann", "die Lüge", "das Reiseziel", "die Wiederholung", "der Verbrauch", "der Bäcker", "die Notiz", "die Pension", "die Mensa", "der Stift", "das Motorrad", "der Schmuck", "der Haupt-", "der Verdienst", "der Blitz", "das Kraftwerk", "der Rabatt", "das Kostüm", "der Zauber", "die Rückfahrt", "der Eimer", "die Spinne", "das Treppenhaus", "der Honig", "der Appetit", "das Buffet", "das Dänemark", "der Prüfer", "das Schach", "der Kiosk", "die Mahnung", "der Schmetterling", "die Haft", "der Unbekannte", "der Schalter", "die Nadel", "die Bestätigung", "das Preisgeld", "das Kabel", "der Rekord", "die Gewohnheit"
];

let germanNounsList24 = [
    "der Zusammenhalt", "der Wirt", "der Schluck", "das Brasilien", "der Standpunkt", "die Präsentation", "das Abonnement", "die Mehrwertsteuer", "die Entlassung", "das Portemonnaie", "die Badewanne", "die Dusche", "der Techniker", "der Zoo", "der Prospekt", "die Heizung", "die Kopie", "die Tastatur", "die Übernachtung", "der Straßenverkehr", "die Schwangere", "der Enkel", "das Hallenbad", "das Schaf", "das Original", "die Beilage", "die Reinigung", "die Bohne", "das Griechenland", "der Comic", "die Fliege", "die Gymnastik", "der Hausmeister", "die Langeweile", "der Spielplatz", "der Vorort", "der Stiefel", "der Lautsprecher", "die Terrasse", "der Monitor", "die Jeans", "der Sonderpreis", "der Schal", "die Kabine", "der Humor", "die Mobilität", "die Ente", "das Lexikon", "die Großeltern, pl.", "die Tomate", "das Pfingsten", "die Diät", "die Grippe", "die Speise", "die Aufforderung", "der Kopfhörer", "der Sonnenschein", "das Gift", "die Maske", "die Panne", "der Kuchen", "die Birne", "die Feder", "der Keks", "der Strauß", "der Herd", "die Waschmaschine", "die Taube", "die S-Bahn", "die Nuss", "die Landstraße", "die Wurst", "der Metzger", "das Doppelzimmer", "der Esel", "der Teig", "die Straßenbahn", "die Briefmarke", "das Lagerfeuer", "die Tankstelle", "der Stau", "der Zauberer", "die Pommes frites", "der Lippenstift", "die Zitrone", "der Fuchs", "die Mütze", "das Schwimmbad", "der Kopfschmerz", "die Rakete", "die Orange", "der Zahnarzt", "die Verspätung", "der Karton", "der Balkon", "das Rezept", "der Briefkasten", "die Besprechung", "die Kreuzung", "das Lenkrad"
];

let germanNounsList25 = [
    "die Postleitzahl", "der Reis", "die Bäckerei", "der Saft", "die Haltestelle", "die Erkältung", "der Automat", "der Drucker", "der Kühlschrank", "das Gewürz", "die Uhrzeit", "die Schokolade", "der Pokal", "der Salat", "die Vorfahrt", "die Begrüßung", "der Wecker", "die Ankunft", "der Pullover", "die Bücherei", "die Beerdigung", "das Sofa", "der Hammer", "die Nudel", "das Schild", "die Heirat", "der Einkauf", "der Schirm", "die Hexe", "der Würfel", "der Beutel", "der Tank", "der Schrei", "der Sonnenuntergang", "der Behälter", "die Dankbarkeit", "die Laufzeit", "das Versehen", "der Ausfall", "die Gattin", "die Rentnerin", "die Handschrift", "der Ausschlag", "die Geisel", "der Sturz", "die Witwe", "das Gespenst", "der Hahn", "der Fingerabdruck", "das Klo", "das Klassenzimmer", "die Handtasche", "der Nachname", "die Kriminalität", "die Festnahme", "der Verstand", "die Würde", "der Versand", "der Quatsch", "die Schnecke", "die Meditation", "der Wasserfall", "die Kleinigkeit", "das Versprechen", "der Ehrgeiz", "das Mikrofon", "die Lektion", "die Kirsche", "die Gurke", "der Helm", "die Flagge", "das Wohlbefinden", "die Priorität", "der Demonstrant", "der Ärmel", "die Schätzung", "das Aroma", "der Arsch", "der Hintern", "der Po", "die Braut", "der Altar", "der Überfall", "die Schande", "der Busch", "der Strauch", "der Teich", "der Zweig", "das Quadrat", "die Fliese", "das Brett", "die Klausur", "das Lotto", "das Gemälde", "der Spargel", "der Notar", "das Testament", "der Akku", "das Zubehör", "der Ruhestand"
];

let germanNounsList26 = [
    "das Hochhaus", "die Massage", "die Applikation", "der Fahrgast", "der Betreiber", "das Telefonat", "das Handeln", "die Flexibilität", "die Toleranz", "die Krankenversicherung", "der Gefangene", "das Mitleid", "die Schlagzeile", "das WLAN", "das Limit", "der Wohlstand", "der Kapitalismus", "der Vorfall", "die Dreharbeit", "die Staatsregierung", "die Schlacht", "der Favorit", "das Feuerwerk", "die Lunge", "das Honorar", "die Gans", "der Kommunismus", "das Paradies", "die Gewähr", "die Abkürzung", "der Schatz", "das Verzeichnis", "das Exemplar", "der Wasserstoff", "die Zuverlässigkeit", "das Wohnmobil", "die Klarheit", "der Vorrat", "der Landtag", "der Keim", "der Irrtum", "das Missverständnis", "die Aufschrift", "die Gewährleistung", "der Vorfahr", "das Theaterstück", "das Arbeitsverhältnis", "der Säugling", "die Emotion", "der Neid", "die Bucht", "der Erwerb", "die Geografie, Geographie", "die Polizistin", "das Teilchen", "die Anwältin", "die Informationstechnologie, IT", "die Stasi", "der Schreck", "die Heldin", "die Gleichung", "die Wechselwirkung", "das Gebirge", "der Personenkraftwagen, PKW", "das Atom", "die Differenzierung", "die Gliederung", "die Skala", "die Vermieterin", "der Dolmetscher", "die Germanistik", "die Hypothese", "die Kassette", "das Diplom", "die Koralle", "die Köchin", "die Relation", "das Riff", "der Fahrschein", "die Klassenarbeit", "die Zahnbürste", "der Sonder-", "das Latein", "der Braten", "die Vanille", "der Schnupfen", "der Schinken", "die Zange", "der Wetterbericht", "der Knödel", "der Wassermann", "das Vollkornbrot", "die EC-Karte", "das Einzelkind", "die Zahncreme", "das Heimweh", "die Umsicht", "das Fundbüro", "der Lerner", "die Eule"
];

let germanNounsList27 = [
    "der Zahnschmerz", "die Urgroßmutter", "der Lappen", "die Notaufnahme", "der Spezial-", "der Ober", "die Brieftasche", "die Anrede", "der Abreisetag", "der Ausflügler", "der Briefumschlag", "das Vorstellungsgespräch", "die Ablenkung", "die Tram", "die Gebrauchsanweisung", "das Müsli", "die Karotte", "die Aggressivität", "die Feigheit", "das Sternzeichen", "der Mechaniker", "der Widder", "die Sucht", "der Kopierer", "der Gesamt-", "der Speisewagen", "das Schmerzmittel", "das Krokodil", "das Gebäck", "das Musikinstrument", "die Musikrichtung", "der Urgroßvater", "der Zeiger", "das Schnitzel", "der Skorpion", "der Steward", "die Salbe", "die Bedienungsanleitung", "die Müllabfuhr", "der Traumberuf", "die Schwiegereltern", "der Essig", "das Sparschwein", "die Avocado", "der Schwager", "die Fußgängerampel", "die Gabel", "die Notrufnummer", "der Schwiegervater", "der Gehsteig", "der Rückenschmerz", "die Erledigung", "der Abfalleimer", "die Schote", "der Babysitter", "der Öko-", "der Gatte", "der Geiz", "das Verkehrszeichen", "die Quittung", "der Donner", "der Geldautomat", "die Dreiviertelstunde", "der Korridor", "die Nachhilfe", "die Zahnpasta", "der Krankenwagen", "der Strumpf", "die Einbahnstraße", "die Vorspeise", "der Enkelsohn", "die Anteilnahme", "das Urlaubsfoto", "das Sonderangebot", "das Intervall", "die Sozialkunde", "der Nationalfeiertag", "der Kaiserschnitt", "die Muttersprache", "das Oberteil", "der Motorroller", "die Bankleitzahl", "das Leitungswasser", "das Quiz", "das Taschengeld", "die Konfitüre", "der Zeitvertreib", "das Hackfleisch", "die Annonce", "der Praktikant", "das Streichholz", "die Jugendherberge", "der Stadtplan", "der Steinbock", "die Giraffe", "die Durchsage", "der Fotoapparat", "der Bikini", "die Großzügigkeit", "der Reiseführer"
];

let germanNounsList28 = [
    "die Rezeption", "die Enkeltochter", "der Einfall", "die Fundsache", "die Verabredung", "die Kanne", "der Umtausch", "das Kuvert", "die Einzahlung", "die Waffel", "der Laib", "der Strafzettel", "das Abgas", "das Einzelzimmer", "die Fahrkarte", "die Drogerie", "die Limonade", "die Klingel", "das Laufwerk", "das Girokonto", "die Schwiegermutter", "die Ungeduld", "die Ehrlichkeit", "die Aushilfe", "die Glückszahl", "das Geburtsjahr", "der Intensivkurs", "die Nachspeise", "das Spezialgebiet", "der Bauchschmerz", "der Postbote", "das Souvenir", "der Profisportler", "die Aprikose", "die Papiertüte", "der Föhn", "der Cousin", "der Kloß", "der Traum-", "das Mineralwasser", "die Socke", "die Reklame", "das Picknick", "der Familienstand", "der Wochentag", "die Verzeihung", "die Margarine", "der Nachtisch", "das Trinkgeld", "die Schildkröte", "die Möhre", "das Parfüm", "der Schwiegersohn", "das Wörterbuch", "der Ehepartner", "die Kantine", "der Mauszeiger", "das Feuerzeug", "der Tagesablauf", "die Ameise", "der Stundenplan", "der Kuli", "die Scherbe", "die Mayonnaise", "die Pfütze", "die Pflaume", "die Schwiegertochter", "das Waschmittel", "der Stecker", "die Wettervorhersage", "die Vollzeit", "der Hausmann", "die Arbeitserlaubnis", "der Detektiv", "der Rosenkohl", "die Mülltonne", "der Abflug", "der Familienname", "das Einschreiben", "das Inserat", "die Halbpension", "der Briefträger", "der Geburtsort", "der Sprudel", "die Aufrichtigkeit", "die Ermäßigung", "das Suchtmittel", "die Mappe", "der Ketchup", "das Prost", "der Nichtraucher", "die Geschwindigkeitsbeschränkung", "die Verschwendung", "die Nichte", "das Milchprodukt", "die Körpergröße", "die Klassenfahrt", "der Wortschatz", "die Schachtel", "die Semmel"
];

let germanNounsList29 = [
    "das Konsulat", "die Mailbox", "der Krankenpfleger", "der Besen", "der Halsschmerz", "der Husten", "die Vase", "der Kugelschreiber", "das Veilchen", "die Glatze", "die Fensterscheibe", "die Bettdecke", "die Delle", "die Beule", "der Bleistift", "die Konserve", "das Doppelbett", "das Zebra", "das Schließfach", "die Handschelle", "das Alphabet", "das Halteverbot", "der Fingernagel", "der Notausgang", "die Sommersprosse", "der Heiratsantrag", "das Taschentuch", "die Weltkugel", "das Butterbrot", "der Müllmann", "der Anrufbeantworter", "die Umweltverschmutzung", "das Kleingeld", "die Locke", "das Hähnchen", "der Kamm", "der Kursleiter", "der Blumenkohl", "das Glücksspiel", "die Bürste", "das Spiegelei", "die Traurigkeit", "das Fegefeuer", "die Schminke", "der Schaum", "die Narbe", "der Streber", "die Erschöpfung", "die Cousine", "die Praktikantin", "die Schwägerin", "die Stewardess", "die Enkelin", "die Wirtin", "die Pflegerin", "die Kellnerin", "die Kauffrau", "die Zuneigung", "die Geschicklichkeit", "die Wiedergutmachung", "der Versager", "das Süddeutschland", "der Dachboden", "der Pfannkuchen", "die Unterhose", "die Fessel", "das Raumklima", "das Wohnheim", "die Düne", "der Aberglaube", "die Begabung", "der Hagel", "der Zeh", "die Ferse", "das Thermometer", "die Wassermelone", "die Ananas", "die Melone", "die Aubergine", "die Olive", "das Steak", "das Sprichwort", "das Arbeitszimmer", "die Geschmacksrichtung", "die Schaufel", "das Lampenfieber", "das Gesäß", "der Bräutigam", "das Brautpaar", "das Radiergummi", "die Brombeere", "das Rechteck", "die Tapete", "das Schachbrett", "die Glühbirne", "der Tresor", "das Durchhaltevermögen", "der Schaffner", "das Rauschen", "der Brei"
];

let germanNounsList30 = [
    "der Wendepunkt", "die Ruhestörung", "die Gage", "die Helligkeit", "die Himmelsrichtung", "die Umkleidekabine", "das Navigationssystem", "die Redewendung", "die Stellenanzeige", "die Eifersucht", "die Verletzbarkeit", "der Schwangerschaftstest", "der Ohrenschmerz", "die Schularbeit", "der Antwortbogen", "der Standardbrief", "der Zimmerschlüssel", "die Zweitsprache", "die Getränkekiste", "der Textaufbau", "die Versichertenkarte", "der Schluckauf", "die Gelenkigkeit", "die Babysitterin", "das Dingsbums", "die Eselsbrücke", "der Korkenzieher"
];